name: agent image

on:
  pull_request:
    paths:
      - images/dev/**
      - images/agent/**
      - test/agent/**
      - package.json
      - package-lock.json
      - .github/workflows/agent-image.yml
      - .github/actions/setup/**
  workflow_dispatch:

jobs:
  agent-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup

      - run: npm run build:dev

      - run: npm run tag:agent-base

      - run: npm run build:agent

      - run: npm run test:agent
