name: scripts

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup

      - run: npm run test:scripts
